Bpi\ApiBundle\Domain\Aggregate\ProfileDictionary:
#  db: documents
  repositoryClass: Bpi\ApiBundle\Domain\Repository\ProfileDictionary
  collection: ProfileDictionary
  fields:
    id:
      id: true
    audiences:
      type: collection
    categories:
      type: collection
