Bpi\ApiBundle\Domain\Aggregate\Agency:
#  db: documents
  repositoryClass: Bpi\ApiBundle\Domain\Repository\AgencyRepository
  collection: Agency
  fields:
    id:
      id: true
    name:
      type: string
    moderator:
      type: string
    secret:
      type: string
    public_key:
      type: string
      unique:
        order: desc
