Bpi\ApiBundle\Domain\Entity\Profile:
  type: embeddedDocument
  fields:
    yearwheel:
      embedded: true
      type: one
      strategy: pushAll
      targetDocument: Bpi\ApiBundle\Domain\ValueObject\Yearwheel
  embedMany:
    tags: ~

