Bpi\ApiBundle\Domain\Entity\Resource:
  type: embeddedDocument
  fields:
    title:
      type: string
    body:
      type: string
    teaser:
      type: string
    ctime:
      type: date
    assets:
      reference: true
      type: many
      targetDocument: Bpi\ApiBundle\Domain\Entity\Asset
      cascade: all
      strategy: pushAll
  lifecycleCallbacks:
    postLoad: [ wakeup ]
