Bpi\ApiBundle\Domain\Entity\Profile\Taxonomy:
  type: embeddedDocument
  fields:
    audience:
      embedded: true
      type: one
      strategy: pushAll
      targetDocument: Bpi\ApiBundle\Domain\ValueObject\Audience
    category:
      embedded: true
      type: one
      strategy: pushAll
      targetDocument: Bpi\ApiBundle\Domain\ValueObject\Category
  lifecycleCallbacks:
    postLoad: [ wakeup ]
