bpi_admin:
    resource: "@BpiAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

bpi_api:
    resource: Bpi\ApiBundle\Controller\RestController
    type: rest

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

logout:
    pattern: /admin/logout

bpi_api_images:
    pattern: /images/{file}.{ext}
