security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        agencies:
            id: bpi.pk.security.user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        documentation:
            pattern:  ^/.+\.html$
            security: false
            
        schema:
            pattern: ^/shema.*
            security: false

        api:
            pattern:   ^/.*
            pk:      true
            stateless: true
