parameters:
#    bpi_admin.example.class: Bpi\AdminBundle\Example

services:
#    bpi_admin.example:
#        class: %bpi_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
